services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=dev
    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=messages
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_ROOT_USERNAME=dev
    ports:
      - "27017:27017"