###
GET http://localhost:8080/api/v1/users
Content-Type: application/json
X-API-KEY: 2cbb1a9e-b0a4-4050-92e5-05a9706102f5

###
GET http://localhost:8080/api/v1/users/1
Content-Type: application/json
X-API-KEY: 2cbb1a9e-b0a4-4050-92e5-05a9706102f5

###
POST http://localhost:8080/api/v1/users
Content-Type: application/json
X-API-KEY: 2cbb1a9e-b0a4-4050-92e5-05a9706102f5

{
  "name": "Hellboy6677"
}

###
GET http://localhost:8080/api/v1/info
Content-Type: application/json
X-API-KEY: 2cbb1a9e-b0a4-4050-92e5-05a9706102f5

###
POST http://localhost:8080/api/v1/channels
Content-Type: application/json
X-API-KEY: 2cbb1a9e-b0a4-4050-92e5-05a9706102f5

{
  "name": "No boss group"
}

###
GET http://localhost:8080/api/v1/userchannel/users?channelId=1
Content-Type: application/json
X-API-KEY: 2cbb1a9e-b0a4-4050-92e5-05a9706102f5

###
POST http://localhost:8080/api/v1/userchannel/join?channelId=1&userId=1
Content-Type: application/json
X-API-KEY: 2cbb1a9e-b0a4-4050-92e5-05a9706102f5


###
WEBSOCKET ws://localhost:7001/api/v1/messages/chat.send
X-API-KEY: 2cbb1a9e-b0a4-4050-92e5-05a9706102f5

SEND
{
  "clientId": 0,
  "channelId": 1,
  "userId": 2,
  "message": "hello"
}

###
WEBSOCKET ws://localhost:8080/api/v1/messages/chat.receive
X-API-KEY: 2cbb1a9e-b0a4-4050-92e5-05a9706102f5

SEND
{
  "clientId": 0,
  "channelId": 1
}

RECEIVE