services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=messages
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_ROOT_USERNAME=dev
    ports:
      - 27017:27017
